### ISSUE TITLE
Video does not play on mobile devices

### ISSUE THREAD

**Issue by IntelOrca** [OpenRCT2/openrct2.github.io#10]
- iOS, both Chrome and Safari load first frame of video but do not play it.
- Android, Chrome does not load video and is just black background.

I think there should be a default background image which is the first frame of the video until the video loads (if successful) and plays.

**Comment by danielsarsi** [comment]
I think mobile prevents autoplay (mobile network bandwidth $$$).
Either way, a proper `poster` attribute for the `<video>` should be set.

Maybe a fallback to a static screenshot on mobile?

**Comment by IntelOrca** [comment]
Yeah probably fallback to an image then unless there is a way of auto playing it.
Similar website: http://launch.mlh.io
