### ISSUE TITLE
make sure the page is compatible with latest jekyll/kramdown

### ISSUE THREAD

**Issue by janisozaur** [OpenRCT2/openrct2.github.io#15]
See https://github.com/blog/2100-github-pages-now-faster-and-simpler-with-jekyll-3-0

> Starting May 1st, 2016, GitHub Pages will only support kramdown, Jekyll's default Markdown engine.

I'm not familiar with this project, so can please someone verify and tick it off?

**Comment by IntelOrca** [comment]
We don't use Jekyll.

**Comment by danielsarsi** [comment]
Should not be a problem, since we don't use Jekyll.

**Comment by janisozaur** [comment]
ok then, thanks.

**Comment by danielsarsi** [comment]
sure :smile:
