### ISSUE TITLE
The "Tips & tricks" section of Getting Started doesn't load the first image

### ISSUE THREAD

**Issue by bryant1410** [OpenRCT2/openrct2.github.io#49]
The first image in Getting Started -> "4 | Tips & tricks" doesn't load for me. It gives a 403 HTTP status code. This is its link: https://camo.githubusercontent.com/a3fed282f826eaa4eb6f155bc55035dce7970263/687474703a2f2f692e696d6775722e636f6d2f544663597644762e706e67

**Comment by tupaschoal** [comment]
Thanks for reporting @bryant1410 and sorry it took us a while to tend to it :)
